yamafaktory/jql

- .gitignore
- src/utils.rs
fixed https://github.com/yamafaktory/jql/issues/1
Ｆile's name is case sensitivity in linux
> fixed no file or directory found　#issues1

- Cargo.toml
- README.md
- src/cli.rs
- src/main.rs
Provide a way to output inlined JSON content.
> Inline output

- .travis.yml
- Cargo.toml
- README.md
- src/apply_filter.rs
- src/array_walker.rs
- src/cli.rs
- src/core.rs
- src/get_selection.rs
- src/group_walker.rs
- src/main.rs
- src/parser.rs
- src/range_selector.rs
- src/utils.rs
- Switch the project to Rust 2018
- Address #14
> Rust 2018 and stdin support

- .travis.yml
- src/main.rs
This should fix https://github.com/yamafaktory/jql/pull/17#issuecomment-445822694.
> Multiline stdin

- src/core.rs
- src/grammar.pest
- src/parser.rs
- Allow an object's properties to be accessed via a filter.
> Properties access in filters

- .travis.yml
- Cargo.lock
- Cargo.toml
- src/bin.rs
- Allow reading multiple lines by deserializing a stream as JSON values (https://docs.serde.rs/serde_json/struct.StreamDeserializer.html).
- Should fix #26.
> Allow streaming by line

- Cargo.lock
- Cargo.toml
- LICENSE-MIT
> chore: update dependencies and add license 📖

- Cargo.lock
- Cargo.toml
> chore: update dependencies and keywords

- README.md
Thanks @frol!
As discussed in #41.
> chore(readme): add Archlinux install instructions

- Cargo.lock
- Cargo.toml
> chore: use license instead of license-file

- Cargo.lock
- Cargo.toml
- src/bin.rs
> chore: fix exit code on errors

- README.md
> chore: fix bad ouput in readme example

- Cargo.lock
- src/apply_filter.rs
- src/bin.rs
- src/flatten_json_array.rs
- src/get_selection.rs
- src/group_walker.rs
- src/lib.rs
> Format better, remove unnecessary borrows and update dependencies

- src/utils.rs
Hi :-) 
I add tests in `src/utils.rs`.
> test(utils) Add tests

- src/range_selector.rs
Hi :-)
I added tests in `src/range_selector.rs`
> test(range_selector): Add tests

- src/array_walker.rs
Hi :-)
Add tests in `src/array_walker.ts`
> test(array_walker): Add tests

- Cargo.lock
- Cargo.toml
- src/cli.rs
This probably warrants a new release because currently running `cargo install jql` will fail (it ignores the `Cargo.lock`!)
Compiler errors for future reference:
```
error[E0432]: unresolved imports `clap::crate_authors`, `clap::crate_description`, `clap::crate_name`, `clap::crate_version`
--> src/cli.rs:1:12
|
1 | use clap::{crate_authors, crate_description, crate_name, crate_version, App, Arg, ArgMatches};
|            ^^^^^^^^^^^^^  ^^^^^^^^^^^^^^^^^  ^^^^^^^^^^  ^^^^^^^^^^^^^ no `crate_version` in the root
|            |              |                  |
|            |              |                  no `crate_name` in the root
|            |              no `crate_description` in the root
|            no `crate_authors` in the root
error: cannot determine resolution for the macro …
```
> Update for clap 3.0.0-rc.4 API changes

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- echo
- src/bin.rs
- src/panic.rs
> fix(broken-pipe): add workaround, CI test and update dependencies

- Cargo.toml
- src/bin.rs
> fix(serde): use feature and adjust deserializer accordingly to disable recursion limit

- Cargo.lock
- Cargo.toml
- benches/benchmark.rs
- src/array_walker.rs
- src/bin.rs
- src/core.rs
- src/get_selection.rs
- src/group_walker.rs
- src/lib.rs
- src/parser.rs
- src/range_selector.rs
- src/types.rs
- tests/integration.rs
> feat(lib): expose more methods

- src/bin.rs
- src/cli.rs
1. add new flag `from-file`
2. change `render_output` to async
3. be able to read contents from a file as selectors
> feature: flag `--from-file`

- src/apply_filter.rs
- src/core.rs
> fix(lens): fix issue with filter and add test

- src/apply_filter.rs
- src/types.rs
Add tests in `src/apply_filter.ts`
> test(apply_filter): Add tests

- .github/workflows/release.yml
- README.md
- crates/jql-runner/src/array.rs
- crates/jql-runner/src/runner.rs
> fix(array+release): only return single index and adjust release artifacts

- Cargo.lock
- Cargo.toml
- README.md
- crates/jql-parser/src/combinators.rs
- crates/jql-parser/src/parser.rs
- crates/jql-parser/src/tokens.rs
- crates/jql-runner/src/array.rs
- crates/jql-runner/src/runner.rs
- crates/jql/Cargo.toml
- crates/jql/src/args.rs
- fuzz/Cargo.lock
This PR will basically help with #224 .
> chore(lenses): allow subset of selectors in lenses

- .github/workflows/ci.yml
- .github/workflows/release.yml
- Introduce new audit job
- Replace deprecated `actions-rs/toolchain@v1` with `dtolnay/rust-toolchain`
- Update `actions/checkout` to `v4`
- Introduce caching with `Swatinem/rust-cache@v2`
- Update `peter-evans/create-pull-request` to `v5`
- Replace deprecated `actions-rs/cargo@v1` with `cross`
> chore(github): update workflows

- Cargo.lock
- crates/jql-parser/Cargo.toml
- crates/jql-parser/src/combinators.rs
- crates/jql-parser/src/parser.rs
- crates/jql-parser/src/tokens.rs
This is follow-up PR based on the feedback from #245.
> chore(jql-parser): improve parser implementation based on @epage 's feedback
